### ISSUE TITLE
supporting classes

### ISSUE THREAD

**Issue by KolorowyAleksander** [mrugacz95/Marcin-Language#1]
Hello, I'm a big fan of the language! My only concern about it is when will we get object oriented support. Maybe next release cycle? 
Sincerely
A big fan!

**Comment by KolorowyAleksander** [comment]
bump

**Comment by mrugacz95** [comment]
Very first I'd like to add functional programming, but maybe I'll also include OOP.
Best regards!

**Comment by KolorowyAleksander** [comment]
:(
